services:
  # Postgres database
  postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
  # Node application
  api:
        build: ./
        image: docker.io/supriyoibm/simple-blog-api
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_HOST=postgres
            - POSTGRES_DB=simple_blog_api
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_PORT=5432
            - PORT=3000
        ports:
            - "3050:3000"