-   hosts: all
    become: yes # Become admin?
    tasks:
        -   name: Create a user
            user:
                name: testuser
                groups: wheel
                append: true